name: Build Linux Mainline Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-kernel:
    runs-on: ubuntu-20.04  # ✅ 这里改为 Ubuntu 20.04

    env:
      ARCH: arm64
      KERNEL_VERSION: "v6.15"  # 也可以写 main 或 v6.x

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential openssl pkg-config libssl-dev libncurses-dev minizip libelf-dev flex bison libc6-dev libidn11-dev rsync bc lz4 debootstrap git \
            gcc-aarch64-linux-gnu dpkg-dev dpkg qemu-user-static \
            debhelper-compat libdw-dev libssl-dev wget curl
          
          git clone --depth=1 -b 6.15/main https://proxy.lukeu.space/github.com/msm8953-mainline/linux.git kernel
