name: Build Linux Mainline Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-kernel:
    runs-on: ubuntu-20.04

    env:
      ARCH: arm64
      KERNEL_VERSION: "main"

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential openssl pkg-config libssl-dev libncurses-dev minizip libelf-dev flex bison libc6-dev libidn11-dev rsync bc lz4 debootstrap git \
            gcc-aarch64-linux-gnu dpkg-dev dpkg qemu-user-static \
            debhelper-compat libdw-dev ccache wget curl

      - name: Restore ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ env.KERNEL_VERSION }}-${{ env.ARCH }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ env.ARCH }}

      - name: Clone kernel source
        run: |
          git clone --depth=1 --branch ${KERNEL_VERSION} https://github.com/msm8953-mainline/linux.git kernel
          cd kernel

      - name: Configure kernel
        run: |
          cd kernel
          make ARCH=${ARCH} CROSS_COMPILE="ccache aarch64-linux-gnu-" defconfig

      - name: Build kernel
        run: |
          cd kernel
          make -j$(nproc) ARCH=${ARCH} CROSS_COMPILE="ccache aarch64-linux-gnu-"
